version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: maritime-traffic-postgres
    environment:
      POSTGRES_DB: maritime_traffic
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: maritime-traffic-backend
    depends_on:
      - postgres
    environment:
      APP_PORT: 8080
      APP_MULTITHREADED: "true"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: maritime_traffic
      DB_USER: monitor
      DB_PASSWORD: monitor_pass
      DB_SSLMODE: disable
    ports:
      - "8080:8080"

volumes:
  postgres_data: